### ISSUE TITLE
Remove outdated platforms

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#115]
The `main` branch of this repository should contains only platforms which are currently accessible (regardless of the status of the calibration). Currently we know that `spinq10q`, `qw5q_gold` and `iqm5q` are operative. 
What is the status of all `tii*` platforms @JavierSerranoGarcia @aorgazf @DavidSarlle?
If they are not operative we should remove them as soon as possible. There is no point in maintaining dead platforms in `main`.
Keep in mind that if we ever need those platforms again it is very easy to jump back to previous version and find them in GitHub.

**Comment by aorgazf** [comment]
Hi @andrea-pasquale, @scarrazza, @Edoardo-Pedicillo @stavros11, 
 
Right now, the following queues are not connected to control electronics; @DavidSarlle has deleted them:
- tii1q_b1
- tiidc
- tii2q
- tii2q1
- tii2q2
- tii2q3
- tii2q4

We will create a new queue for the 2 single qubits installed in the XLD1000. One of these chips has been characterised with the VNA and is now being connected to a qblox cluster. The other one is being characterised now with the VNA. We plan to connect it to qblox too. David will create a new queue for them `tii1qs_xld1000`.

David explained the problem that having a queue without working electronics poses to the software team, so we thought of the following solution:

- A queue will exist only if it is connected to a QPU and control electronics.
- If there is a problem with the control electronics, the queue will be drained.
- If there is a problem with the fridge, the queue will remain undrained to allow software testing.
- The way users can tell if a chip is characterised is if there is a corresponding platform in https://github.com/qiboteam/qibolab_platforms_qrc `main`
- In order to allow the team of the lab to test different electronics and carry out other experiments, we will create test queues, one per fridge:
  tests_xld1000
  tests_xld400
  tests_sd250
In these queues the software team should not expect to find control electronics.

Let me know if you have any concerns about this plan.

**Comment by stavros11** [comment]
Thanks @aorgazf @DavidSarlle. This plan sounds good, my only concern is that for me it is useful to have at least one queue for electronics that are not connected to any qubits or fridge. I have been using the `tiidc` queue to run tests and benchmarks on Quantum Machines because I noticed that no one was using this queue. Now I cannot do this anymore so I’ll have to use some other queue that is connected to qubits and potentially interfere with people trying to use them. This shouldn’t be needed since we are using different electronics.

**Comment by andrea-pasquale** [comment]
Thanks @aorgazf @DavidSarlle.

Generally I like the proposal but I need to understand better a few things.

> * The way users can tell if a chip is characterised is if there is a corresponding platform in https://github.com/qiboteam/qibolab_platforms_qrc `main`

I don't know exactly what you mean here by `characterised` but with the current problems that we have we might be facing an `empty` `main` for a long time if we allow to have in `main` only `characterised` chips. For the time being we might consider to have in `main` just working platforms with "low" fidelities.

> * In order to allow the team of the lab to test different electronics and carry out other experiments, we will create test queues, one per fridge:
>       tests_xld1000
>       tests_xld400
>       tests_sd250
>       In these queues the software team should not expect to find control electronics.

Unless something changed there is still just one network adapter, correct? I'm expecting that whenever the lab team needs to perform an experiment the corresponding `standard` queues will be drained, correct? Otherwise we could have conflicts between jobs if someone tries to access a device where there is an ongoing experiment. Could you please elaborate a bit more on how you are planning to use those new queues?

Maybe a bit unrelated to the issue itself but we could also consider to introduce specifics tags in this repository to track the status of the lab. For every warm up or cooldown we might have a new tag.

**Comment by andrea-pasquale** [comment]
> > Maybe a bit unrelated to the issue itself but we could also consider to introduce specifics tags in this repository to track the status of the lab. For every warm up or cooldown we might have a new tag.
> 
> In case you want to do that, let's discuss it first, because that's exactly the 2D problem I mentioned earlier...
> 
> [#110 (comment)](https://github.com/qiboteam/qibolab_platforms_qrc/pull/110#issuecomment-1914791531)
> 
> (i.e. you'd like to be able to use multiple versions of Qibolab with the same lab, in particular the current one)

Yes, I forgot. For sure we have this problem. Actually I was not thinking about versions for qibo packages, I mainly wanted to log somewhere which devices were used for a certain amount of time. 

As long as we have one qibocal report to reference each platform the problem should be solved given that qibocal will show in the report all versions currently used btw.

**Comment by alecandido** [comment]
Well, I'm not saying we shouldn't do it, it's a reasonable request to establish compatibility, with both lab and Qibolab, since they are both changing.

From the Qibolab point of view, we already have a version, with the greater detail of semver. But we'll need a version even for the lab (an integer is fine, semver not needed).

But the two will be slightly different: we could use multiple Qibolab versions at a time, but only one lab, the latest (though a new version of the lab might not destroy all runcards, because maybe only one fridge will warm up).

So, a possible solution could be:
- we might have multiple branches for the supported versions of Qibolab
- with `main` being associated with the stable version
- and release one tag per active branch every time we need to roll a new version of the lab (i.e. we tag the version we're abandoning, for historic purpose, since the current version will be kept up to date in the active branches)

**Comment by scarrazza** [comment]
@DavidSarlle @aorgazf thanks, please check https://github.com/qiboteam/qrccluster/issues/161#issuecomment-1933742222

**Comment by scarrazza** [comment]
@andrea-pasquale , I had chat with @alecandido and we could limit access to specific queues for a general user using the current slurm QOS, and create another group (dev group) with full access to all partitions.

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale , I had chat with @alecandido and we could limit access to specific queues for a general user using the current slurm QOS, and create another group (dev group) with full access to all partitions.

Indeed I also discussed a similar approach with @alecandido.
Perhaps it would be interesting to have a general queue just for the SD given that usually no platforms are ever pushed for that fridge given they change very often

**Comment by DavidSarlle** [comment]
Regarding the queues protocol. After discussing with @stavros11 @alecandido @aorgazf in person and taking into account all the comments, we have created this proposal for the queues that needs to be discussed tomorrow during the weekly meeting, but feel free to comment before the meeting:

**Slurm Queues Protocol**

Cluster queues
-	Simulation queues
-	1 queue per “production” chip. Labelled as the chip (iqm5q, qw5q_gold, spinq10q…)
-	1 queue per available electronics. Use for testing new “development” chips (software/fabrication). Labelled as “electronics_tests”.

**Stable queues (iqm5q, qw5q_gold, spinq10q)**
1.	The current characterization status can be checked with qpu_status webapp
2.	Always up even if they are not fully characterized 
(characterization at least approved in qibolab platforms main)
3.	Queue drained if the platform is not available for “computing”.
4.	Lab team oversees draining/undraining these queues

**Development queues (zh_tests, rfsoc_tests, qblox02_tests, qblox03_tests, qblox06_tests, qblox20_tests, qm_tests)**
1.	Multi qiblab-platform queue 
2.	Drained if electronics are allocated for a stable queue.
3.	Lab team is in charge of draining/undraining these queues.

(TODO after approval the protocol: drain zh_test queue, qblox03 and qblox_06)

**Comment by alecandido** [comment]
I didn't get the nuance of "oversees" vs "in-charge". For me the hardware queues depend on the lab state, that is managed by the lab team, so it is fine in general to be managed by the lab team (of course with some kind of coordination, whenever possible).

The stable vs development queues are even fine to me, they could simply cause a synchronization overhead on the people managing the queues, because you need multiple operations to step from a valid state into another valid state (activate one, while draining another).

However, this could also be automated (if needed), but for the time is even fine just relying on careful maintainers :) 

> After discussing with @stavros11 @alecandido @aorgazf in person

I guess it's a typo, or I just misunderstood :P
It is unfortunately difficult for me to discuss in person with you right now...

**Comment by DavidSarlle** [comment]
After discussing again today, the new protocol has bee implemented and approved. New queues created and removed outdated ones

**Comment by andrea-pasquale** [comment]
Would it be possible to clean up `main` to understand which platforms are currently available?

**Comment by alecandido** [comment]
Even merging some PRs, would be great 🗡️ 

Even some that haven't reached any *final* state, but for which a whatever calibration exists (assuming that the chip+electronics in the lab is available, and not yet scheduled for changes)

**Comment by andrea-pasquale** [comment]
Implemented in #141
