### ISSUE TITLE
Bot measurements

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab_platforms_qrc#72]
@andrea-pasquale or @stavros11 could we made the bot measure T1 and RB single qubit apart from assigment fidelity ?

**Comment by andrea-pasquale** [comment]
Possible solution: use bot to run runcard and upload report + show link in the message.

**Comment by stavros11** [comment]
> Possible solution: use bot to run runcard and upload report + show link in the message.

That's a good plan, I would just still keep the very basic information (platform name, run time, assignment fidelities and potentially T1, T2) in the bot message, so that it is visible without opening the report. I am mainly thinking the lab where we need to change the cluster address to open the reports (due to being in the same network). But for sure we should also append the uploaded link for more details.

**Comment by Jacfomg** [comment]
Yeah, I can do the message, the upload I'm not so sure about.

**Comment by Jacfomg** [comment]
For some reason RB routines, maybe due to several connections or something takes way longer than expected on the bot. I have no clue what it could be the solution.

**Comment by alecandido** [comment]
The GitHub bot most likely will need to be reviewed completely, since quite some time has passed.

Let's close this, and reopen a new one whenever someone will need the bot again.
